/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libsdhqs_jni_QSLibSDH */

#ifndef _Included_com_libsdhqs_jni_QSLibSDH
#define _Included_com_libsdhqs_jni_QSLibSDH
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libsdhqs_jni_QSLibSDH_init
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libsdhqs_jni_QSLibSDH_terminate
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    enableDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_libsdhqs_jni_QSLibSDH_enableDebugMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getCurStateData
 * Signature: ()Lcom/libsdhqs/jni/QSLibSDH$ExecutionState;
 */
JNIEXPORT jobject JNICALL Java_com_libsdhqs_jni_QSLibSDH_getCurStateData
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getFullRefreshCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libsdhqs_jni_QSLibSDH_getFullRefreshCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getQstFullPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libsdhqs_jni_QSLibSDH_getQstFullPath
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getCurLoc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libsdhqs_jni_QSLibSDH_getCurLoc
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getExprValue
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_libsdhqs_jni_QSLibSDH_getExprValue
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libsdhqs_jni_QSLibSDH_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getCompiledDateTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libsdhqs_jni_QSLibSDH_getCompiledDateTime
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    isInCallBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_isInCallBack
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getMainDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libsdhqs_jni_QSLibSDH_getMainDesc
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    isMainDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_isMainDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getVarsDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libsdhqs_jni_QSLibSDH_getVarsDesc
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    isVarsDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_isVarsDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getVarValuesCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_libsdhqs_jni_QSLibSDH_getVarValuesCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getVarValues
 * Signature: (Ljava/lang/String;I)Lcom/libsdhqs/jni/QSLibSDH$VarValResp;
 */
JNIEXPORT jobject JNICALL Java_com_libsdhqs_jni_QSLibSDH_getVarValues
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getMaxVarsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libsdhqs_jni_QSLibSDH_getMaxVarsCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getVarNameByIndex
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_libsdhqs_jni_QSLibSDH_getVarNameByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    setInputStrText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libsdhqs_jni_QSLibSDH_setInputStrText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getActions
 * Signature: ()[Lcom/libsdhqs/jni/QSLibSDH$ListItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_libsdhqs_jni_QSLibSDH_getActions
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    isActionsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_isActionsChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    executeSelActionCode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_executeSelActionCode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getSelActionIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libsdhqs_jni_QSLibSDH_getSelActionIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    setSelActionIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_setSelActionIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getObjects
 * Signature: ()[Lcom/libsdhqs/jni/QSLibSDH$ListItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_libsdhqs_jni_QSLibSDH_getObjects
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    isObjectsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_isObjectsChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getSelObjectIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libsdhqs_jni_QSLibSDH_getSelObjectIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    setSelObjectIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_setSelObjectIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    execString
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_execString
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    execLocationCode
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_execLocationCode
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    execCounter
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_execCounter
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    execUserInput
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_execUserInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getLastErrorData
 * Signature: ()Lcom/libsdhqs/jni/QSLibSDH$ErrorData;
 */
JNIEXPORT jobject JNICALL Java_com_libsdhqs_jni_QSLibSDH_getLastErrorData
  (JNIEnv *, jobject);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    getErrorDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libsdhqs_jni_QSLibSDH_getErrorDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    loadGameWorldFromData
 * Signature: ([BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_loadGameWorldFromData
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    loadGameWorldFromFD
 * Signature: (Ljava/io/FileDescriptor;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_loadGameWorldFromFD
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    saveGameAsData
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_libsdhqs_jni_QSLibSDH_saveGameAsData
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    saveGameByFD
 * Signature: (Ljava/io/FileDescriptor;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_saveGameByFD
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    openSavedGameFromData
 * Signature: ([BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_openSavedGameFromData
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    openSavedGameFromFD
 * Signature: (Ljava/io/FileDescriptor;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_openSavedGameFromFD
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    restartGame
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libsdhqs_jni_QSLibSDH_restartGame
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libsdhqs_jni_QSLibSDH
 * Method:    selectMenuItem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libsdhqs_jni_QSLibSDH_selectMenuItem
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
